// Email Document System
// Handles emailing documents to users

class EmailDocumentSystem {
    constructor() {
        this.emailProvider = 'mailto'; // Using mailto for client-side email
    }

    // Send document via email
    sendDocumentByEmail(document, userEmail, userName) {
        if (!userEmail) {
            return { success: false, error: 'Email address is required' };
        }

        // Prepare email content
        const subject = encodeURIComponent(`Your Medical Assistance Document - ${document.name}`);
        const body = this.generateEmailBody(document, userName);
        
        // Create mailto link
        const mailtoLink = `mailto:${userEmail}?subject=${subject}&body=${encodeURIComponent(body)}`;
        
        // Open email client
        window.location.href = mailtoLink;
        
        return { success: true, method: 'mailto' };
    }

    // Send multiple documents
    sendMultipleDocuments(documents, userEmail, userName) {
        if (!userEmail) {
            return { success: false, error: 'Email address is required' };
        }

        if (!documents || documents.length === 0) {
            return { success: false, error: 'No documents to send' };
        }

        const subject = encodeURIComponent(`Your Medical Assistance Documents (${documents.length} files)`);
        const body = this.generateMultiDocumentEmailBody(documents, userName);
        
        const mailtoLink = `mailto:${userEmail}?subject=${subject}&body=${encodeURIComponent(body)}`;
        window.location.href = mailtoLink;
        
        return { success: true, method: 'mailto', count: documents.length };
    }

    // Generate email body for single document
    generateEmailBody(document, userName) {
        const name = userName || 'User';
        
        return `Hi ${name},

Here is your medical assistance document:

Document: ${document.name}
${document.description ? `Description: ${document.description}` : ''}
${document.category ? `Category: ${document.category}` : ''}
${document.pages ? `Pages: ${document.pages}` : ''}

${document.helpText ? `\nHelp Text:\n${document.helpText}` : ''}

${document.url ? `\nOfficial Form URL:\n${document.url}` : ''}

${document.content ? `\n--- DOCUMENT CONTENT ---\n\n${document.content}\n\n--- END DOCUMENT ---` : ''}

${document.sections && document.sections.length > 0 ? `\nDocument Sections:\n${document.sections.map((s, i) => `${i + 1}. ${s}`).join('\n')}` : ''}

This document was generated by Medical Assistance Helper.

Best regards,
Medical Assistance Helper Team

---
This tool provides guidance only and does not constitute medical or legal advice.
Always consult with qualified professionals for your specific situation.`;
    }

    // Generate email body for multiple documents
    generateMultiDocumentEmailBody(documents, userName) {
        const name = userName || 'User';
        
        let body = `Hi ${name},

Here are your medical assistance documents (${documents.length} total):

--- DOCUMENTS LIST ---

`;

        documents.forEach((doc, index) => {
            body += `${index + 1}. ${doc.name}
   ${doc.description || ''}
   ${doc.url ? `URL: ${doc.url}` : ''}
   ${doc.helpText ? `Help: ${doc.helpText}` : ''}

`;
        });

        body += `--- END DOCUMENTS LIST ---

For detailed content of each document, please visit the Medical Assistance Helper website or request individual documents.

This was generated by Medical Assistance Helper.

Best regards,
Medical Assistance Helper Team

---
This tool provides guidance only and does not constitute medical or legal advice.
Always consult with qualified professionals for your specific situation.`;

        return body;
    }

    // Create downloadable text file of document
    generateTextFile(document) {
        const content = this.generateEmailBody(document, 'User');
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement('a');
        link.href = url;
        link.download = `${document.name.replace(/[^a-z0-9]/gi, '_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        
        return { success: true };
    }

    // Copy document content to clipboard
    async copyToClipboard(document, userName) {
        const content = this.generateEmailBody(document, userName);
        
        try {
            await navigator.clipboard.writeText(content);
            return { success: true, message: 'Document copied to clipboard' };
        } catch (err) {
            // Fallback for older browsers
            const textArea = document.createElement('textarea');
            textArea.value = content;
            textArea.style.position = 'fixed';
            textArea.style.left = '-999999px';
            document.body.appendChild(textArea);
            textArea.select();
            
            try {
                document.execCommand('copy');
                document.body.removeChild(textArea);
                return { success: true, message: 'Document copied to clipboard' };
            } catch (err2) {
                document.body.removeChild(textArea);
                return { success: false, error: 'Failed to copy to clipboard' };
            }
        }
    }

    // Show email dialog
    showEmailDialog(document, currentUser) {
        const modal = this.createEmailModal(document, currentUser);
        document.body.appendChild(modal);
    }

    // Create email modal
    createEmailModal(doc, currentUser) {
        const modal = document.createElement('div');
        modal.className = 'email-modal';
        modal.style.cssText = `
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0, 0, 0, 0.5);
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 10000;
        `;
        
        const modalContent = document.createElement('div');
        modalContent.style.cssText = `
            background: white;
            border-radius: 12px;
            padding: 2rem;
            max-width: 500px;
            width: 90%;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        `;
        
        const userEmail = currentUser ? currentUser.email : '';
        const userName = currentUser ? currentUser.name : '';
        
        modalContent.innerHTML = `
            <h2 style="margin-top: 0; color: #2d3748;">📧 Email Document</h2>
            <p style="color: #718096; margin-bottom: 1.5rem;">Send "${doc.name}" to your email</p>
            
            <div style="margin-bottom: 1rem;">
                <label style="display: block; font-weight: 600; margin-bottom: 0.5rem; color: #2d3748;">Email Address:</label>
                <input type="email" id="email-address-input" value="${userEmail}" placeholder="your@email.com" 
                       style="width: 100%; padding: 0.75rem; border: 2px solid #e2e8f0; border-radius: 8px; font-size: 1rem;">
            </div>
            
            <div style="display: flex; gap: 0.5rem; flex-wrap: wrap; margin-top: 1.5rem;">
                <button onclick="emailSystem.sendEmailClick('${doc.id}')" class="btn-primary" style="flex: 1; min-width: 120px;">
                    📧 Send Email
                </button>
                <button onclick="emailSystem.downloadTextClick('${doc.id}')" class="btn-secondary" style="flex: 1; min-width: 120px;">
                    💾 Download
                </button>
                <button onclick="emailSystem.copyClipboardClick('${doc.id}')" class="btn-secondary" style="flex: 1; min-width: 120px;">
                    📋 Copy
                </button>
            </div>
            
            <button onclick="emailSystem.closeEmailDialog()" class="btn-secondary" 
                    style="width: 100%; margin-top: 1rem;">
                Close
            </button>
        `;
        
        modal.appendChild(modalContent);
        modal.setAttribute('data-doc-id', doc.id);
        modal.setAttribute('data-doc-name', doc.name);
        
        return modal;
    }

    // Handle send email click
    sendEmailClick(docId) {
        const modal = document.querySelector('.email-modal');
        const email = document.getElementById('email-address-input').value;
        const docName = modal.getAttribute('data-doc-name');
        
        if (!email) {
            alert('Please enter an email address');
            return;
        }
        
        const user = window.authSystem ? window.authSystem.getCurrentUser() : null;
        const document = { id: docId, name: docName };
        
        this.sendDocumentByEmail(document, email, user ? user.name : '');
        this.closeEmailDialog();
    }

    // Handle download click
    downloadTextClick(docId) {
        const modal = document.querySelector('.email-modal');
        const docName = modal.getAttribute('data-doc-name');
        const document = { id: docId, name: docName };
        
        this.generateTextFile(document);
    }

    // Handle copy click
    async copyClipboardClick(docId) {
        const modal = document.querySelector('.email-modal');
        const docName = modal.getAttribute('data-doc-name');
        const user = window.authSystem ? window.authSystem.getCurrentUser() : null;
        const document = { id: docId, name: docName };
        
        const result = await this.copyToClipboard(document, user ? user.name : '');
        
        if (result.success) {
            alert('✓ Document content copied to clipboard!');
        } else {
            alert('Failed to copy: ' + result.error);
        }
    }

    // Close email dialog
    closeEmailDialog() {
        const modal = document.querySelector('.email-modal');
        if (modal) {
            modal.remove();
        }
    }
}

// Initialize global email system
if (typeof window !== 'undefined') {
    window.emailSystem = new EmailDocumentSystem();
}
